### ISSUE TITLE
File not found issues: cricket_flow.npy'

### ISSUE THREAD

**Issue by VijayRameshkumar** [OanaIgnat/i3d_keras#1]
I'm trying to built i3d kinetics in keras.

I'm following instructions as per readme.md file.

it throwing me below error. Could you help me on this?

Traceback (most recent call last):
  File "src/evaluate_sample.py", line 122, in <module>
    main(args)
  File "src/evaluate_sample.py", line 62, in main
    flow_sample = np.load(SAMPLE_DATA_PATH['flow'])
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cricket_flow.npy'
: cannot connect to X server

**Comment by VijayRameshkumar** [comment]
openCV 4.0 beta and alpha versions only has the cv2.DualTVL1OpticalFlow_create() features.

**Comment by VijayRameshkumar** [comment]
I've fixed this issue by using calcOpticalFlowFarneback(prev,curr, None, 0.5, 3, 15, 3, 5, 1.2, 0)
